<h1> <center>Advent of Code 2022</center></h1>
<h3><center> --- Day 8 : Treetop Tree House --- </center></h3>

Challenge link : [https://adventofcode.com/2022/day/8](https://adventofcode.com/2022/day/8).

> The expedition comes across a peculiar patch of tall trees all planted carefully in a grid. The Elves explain that a previous expedition planted these trees as a reforestation effort. Now, they're curious if this would be a good location for a tree house.
> 
> First, determine whether there is enough tree cover here to keep a tree house hidden. To do this, you need to count the number of trees that are visible from outside the grid when looking directly along a row or column.
> 
> The Elves have already launched a quadcopter to generate a map with the height of each tree (your puzzle input). For example:
>
> ```
> 30373
> 25512
> 65332
> 33549
> 35390
> ```
> 
> Each tree is represented as a single digit whose value is its height, where 0 is the shortest and 9 is the tallest.
> 
> A tree is visible if all of the other trees between it and an edge of the grid are shorter than it. Only consider trees in the same row or column; that is, only look up, down, left, or right from any given tree.
> 
> All of the trees around the edge of the grid are visible - since they are already on the edge, there are no trees to block the view. In this example, that only leaves the interior nine trees to consider:
> 
> - The top-left 5 is visible from the left and top. (It isn't visible from the right or bottom since other trees of height 5 are in the way.)
> - The top-middle 5 is visible from the top and right.
> - The top-right 1 is not visible from any direction; for it to be visible, there would need to only be trees of height 0 between it and an edge.
> - The left-middle 5 is visible, but only from the right.
> - The center 3 is not visible from any direction; for it to be visible, there would need to be only trees of at most height 2 between it and an edge.
> - The right-middle 3 is visible from the right.
> - In the bottom row, the middle 5 is visible, but the 3 and 4 are not.
> With 16 trees visible on the edge and another 5 visible in the interior, a total of 21 trees are visible in this arrangement.
> 
> <span style="color: hsl(15, 100%, 72%); font-weight:bold;">Consider your map; how many trees are visible from outside the grid?</span>

In [47]:
import numpy as np

In [48]:
map_data = [[int(tree) for tree in list(line)] for line in open('data.txt').read().split('\n')]

map_data = np.array(map_data)
print(map_data)

[[1 1 0 ... 0 1 0]
 [1 0 2 ... 1 1 2]
 [2 1 0 ... 0 0 2]
 ...
 [0 0 2 ... 1 0 2]
 [2 1 0 ... 0 0 0]
 [2 2 0 ... 0 0 1]]


In [49]:
visibleTreeCount = 4*(len(map_data)-1)

for i in range(1,len(map_data)-1):
    for j in range(1,len(map_data[i])-1):
        if(max(map_data[i,:j])<map_data[i,j] or 
        max(map_data[i,j+1:])<map_data[i,j] or 
        max(map_data[i+1:,j])<map_data[i,j] or 
        max(map_data[:i,j])<map_data[i,j]):
            visibleTreeCount+=1
print(visibleTreeCount)

1851


> --- Part Two ---
> 
> Content with the amount of tree cover available, the Elves just need to know the best spot to build their tree house: they would like to be able to see a lot of trees.
> 
> To measure the viewing distance from a given tree, look up, down, left, and right from that tree; stop if you reach an edge or at the first tree that is the same height or taller than the tree under consideration. (If a tree is right on the edge, at least one of its viewing distances will be zero.)
> 
> The Elves don't care about distant trees taller than those found by the rules above; the proposed tree house has large eaves to keep it dry, so they wouldn't be able to see higher than the tree house anyway.
> 
> In the example above, consider the middle 5 in the second row:
>
> ```
> 30373
> 25512
> 65332
> 33549
> 35390
> ```
> 
> - Looking up, its view is not blocked; it can see 1 tree (of height 3).
> - Looking left, its view is blocked immediately; it can see only 1 tree (of height 5, right next to it).
> - Looking right, its view is not blocked; it can see 2 trees.
> - Looking down, its view is blocked eventually; it can see 2 trees (one of height 3, then the tree of height 5 that blocks its view).
> 
> A tree's scenic score is found by multiplying together its viewing distance in each of the four directions. For this tree, this is 4 (found by multiplying 1 * 1 * 2 * 2).
> 
> However, you can do even better: consider the tree of height 5 in the middle of the fourth row:
>
> ```
> 30373
> 25512
> 65332
> 33549
> 35390
>```
> 
> - Looking up, its view is blocked at 2 trees (by another tree with a height of 5).
> - Looking left, its view is not blocked; it can see 2 trees.
> - Looking down, its view is also not blocked; it can see 1 tree.
> - Looking right, its view is blocked at 2 trees (by a massive tree of height 9).
> 
> This tree's scenic score is 8 (2 * 2 * 1 * 2); this is the ideal spot for the tree house.
> 
> Consider each tree on your map. <span style="color: hsl(15, 100%, 72%); font-weight:bold;">What is the highest scenic score possible for any tree?</span>

In [51]:
score = 1
maxScore=0

for i in range(1,len(map_data)-1):
    for j in range(1,len(map_data[i])-1):
        cpt1=0
        cpt2=0
        cpt3=0
        cpt4=0

        for i1 in range(i-1,-1,-1): # go up
            cpt1+=1
            if(map_data[i1,j]>=map_data[i,j]):
                break

        for i2 in range(i+1,len(map_data)): #go down
            cpt2+=1
            if(map_data[i2,j]>=map_data[i,j]):
                break

        for j1 in range(j-1,-1,-1): #go left
            cpt3+=1
            if(map_data[i,j1]>=map_data[i,j]):
                break

        for j2 in range(j+1,len(map_data[i])): # go right
            cpt4+=1
            if(map_data[i,j2]>=map_data[i,j]):
                break

        score = cpt1 * cpt2 * cpt3 * cpt4
        
        if(score>maxScore):
            maxScore=score
print(maxScore)

574080
